<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'MRBLX\Vendor\Mindspun\Framework\Providers\GlobalsProvider' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Providers/GlobalsProvider.php',
   'MRBLX\Vendor\Mindspun\Framework\Providers\PluginProvider' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Providers/PluginProvider.php',
   'MRBLX\Vendor\Mindspun\Framework\Registry' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Registry.php',
   'MRBLX\Vendor\Mindspun\Framework\Facades\Plugin' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Facades/Plugin.php',
   'MRBLX\Vendor\Mindspun\Framework\Facades\Globals' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Facades/Globals.php',
   'MRBLX\Vendor\Mindspun\Framework\Utils' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Utils.php',
   'MRBLX\Vendor\Mindspun\Framework\Provider' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Provider.php',
   'MRBLX\Vendor\Mindspun\Framework\Autoloader' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Autoloader.php',
   'MRBLX\Vendor\Mindspun\Framework\Facade' => $strauss_src . '/mindspun/wordpress-plugin-framework/src/Facade.php',
);